### ISSUE TITLE
gamepad support

### ISSUE THREAD

**Issue by ogmkp** [vwout/obs-visca-control#1]
Hello and thank you for this script.
Do you think it is possible to add the support for a gamepad? In case I want to control the camera freely?

**Comment by vwout** [comment]
The plugin currently supports recall of a pre-programmed preset. Direct control of the camera is not included at this moment.
Implementing support for a specific gamepad sounds like out of scope for this plugin. What could be possible is to add hotkey support to perform a camera movement action (pan/tilt/zoom) upon keypress. Translation of gamepad action into a keystroke would have to be implemented elsewhere.

**Comment by ogmkp** [comment]
Hotkey support will be a good thing ;)

**Comment by vwout** [comment]
Hotkeys are available as of release 1.3. The actions pan, tilt & zoom can be used. The action is executed when the key is pressed and stops when the key is released. The keys can be assigned in the hotkey settings of OBS.
