### ISSUE TITLE
Increase/Decrease Pan/Tilt Speed not immediately effective

### ISSUE THREAD

**Issue by vwout** [vwout/obs-visca-control#11]
Yesterday, when using the PTZOptics mode, I found that the "Increase Pan/Tilt Speed" adn "Decrease Pan/Tilt Speed"(A) did not take effect immediately on the camera. I need to press the refresh button(C) in the lower left corner to take effect, but the value here has changed（B）.

![微信图片_20230218090822](https://user-images.githubusercontent.com/112599924/219823578-8d6edb3c-90c7-4e7d-acd4-9e49aff558f8.png)

![微信图片_20230218090732](https://user-images.githubusercontent.com/112599924/219823610-8788e210-7f41-4715-a98d-f4eeb5e3460c.png)

_Originally posted by @PoWeR-Ding in https://github.com/vwout/obs-visca-control/issues/8#issuecomment-1435436974_

**Comment by vwout** [comment]
The speed increase/decrease shortcuts actually do have immediate effect. This is only shown in the settings after reload - this is a limitation of OBS.
The speed however was only applied at the first hotkey use. Changing the speed afterwards has no effect until the plugin is reloaded. This bug is resolved in [33c621a](https://github.com/vwout/obs-visca-control/commit/33c621a54b64ce0cf716ffec7bf732b7b0cbf52c).

**Comment by PoWeR-Ding** [comment]
OK, copy. I will test as soon as possible

**Comment by PoWeR-Ding** [comment]
![微信截图_20230219235750](https://user-images.githubusercontent.com/112599924/219959584-3f62b6e5-10a8-4591-a494-e8000729c9f2.png)
![微信图片_20230219235509](https://user-images.githubusercontent.com/112599924/219959590-84842040-bb5e-4897-8c22-3aafa2de34d6.png)

Hello, I can't control the camera after updating the script.

**Comment by PoWeR-Ding** [comment]
Now, after changing the speed, it will take effect immediately. But the up, down, left and right directions cannot be controlled.

![微信截图_20230220001321](https://user-images.githubusercontent.com/112599924/219960357-ab89d852-9e6b-44d9-82b7-77856f003990.png)

**Comment by PoWeR-Ding** [comment]
"Zoom In" and "Zoom Out" are also normal. √

**Comment by vwout** [comment]
Sorry about that; my fix was too quick (not properly tested). Should be resolved now.

**Comment by PoWeR-Ding** [comment]
Never mind, I will continue to test😂😂

**Comment by PoWeR-Ding** [comment]
![微信截图_20230220091752](https://user-images.githubusercontent.com/112599924/219988366-c25f99a5-a1e6-438c-9e90-85710cde48c3.png)
[Script Log.txt](https://github.com/vwout/obs-visca-control/files/10778597/Script.Log.txt)

This time, "Zoom In" and "Zoom Out" will not take effect. 😣 😣 😣 😣

**Comment by vwout** [comment]
Now it should finally work - without breaking stuff.
This finally made me start on writing unit tests for the OBS plugin script as well ...

**Comment by PoWeR-Ding** [comment]
Thanks for the patient repair. I will continue to test it.

**Comment by PoWeR-Ding** [comment]
Good morning, vwut

I tested it again and there was no problem.

Thanks again.
