### ISSUE TITLE
Stop Commands Not Processing

### ISSUE THREAD

**Issue by rtalking10** [vwout/obs-visca-control#13]
When we move scenes the stop command on the custom action does not process leading to the camera not listening to other scenes. If we put a separate scene with the stop command as the start command on a custom action it works

**Comment by vwout** [comment]
Could you describe in a bit more detail which action is executed and what stop action you expect?
Like which action is running that needs stopping and what is on program after the transition.

Do keep in mind that a stop action is *not* executed when the scene on program also uses the same camera with a Visca action (and 'action active' is configured for program only or the Visca scene does not use the same camera with a Visca action).

**Comment by rtalking10** [comment]
So we are running a humanoid tracking command (81 0A 11 54 02 FF) that turns on on preview due to a camera pop up we then switch it to on program after the pop up goes away. The stop command (81 0A 11 54 03 FF) should stop the humanoid tracking and throw up another pop up. We are going to a PowerPoint scene or a different camera that isn't on humanoid tracking on program when we want the tracking to stop.

**Comment by vwout** [comment]
That's a nice application for the custom commands!

What are your settings for the `action options`? Is action active always, preview or program? And did you tick the item to only run the action on preview when the camera is not active on program?

I'd like to be sure about what is going on, but I think I understand why it is not working the way you expect.

**Comment by rtalking10** [comment]
We've tried always and on preview only with the tick box both checked and unchecked

**Comment by vwout** [comment]
After some investigation I found the handling of start and stop handling to not be consistently processed. Commit afbc8b0b5f6e0148e7e32094f869634ecf7075a7 improves this and adds an overview of action execution and conditions to the documentation.

I think for you situation you need to configure the actions on `Action Active: Always`, with checkbox `On preview exclusive: No`. Then I assume that your camera does not show the popup again when 'humanoid tracking' is already active.
In case the camera does show it again, use `Action Active: Preview`, with checkbox `On preview exclusive: No`, but then the tracking will only be disabled when you load a next scene in preview.

The above requires that you update the scripts to the latest code on Github. There are some open items, for example processing of actions while Multiview is active. Next to that, quite some changes were made to the handling of events, so the new code might have new issues (therefore it is not released yet). 
Feel free to test it. Be sure to test it before trying it live.

**Comment by rtalking10** [comment]
Thank you for your time and effort. We will be testing this at some point in the next week or two and will update you if we find anything

**Comment by vwout** [comment]
@rtalking10 Have you by any chance been able to confirm the functionality in the mean time?

**Comment by rtalking10** [comment]
We were able to test this recently. It was working as expected without multi view. It doesn't work with multi view but if I remember correctly you mentioned that is a known limitation. We have been discussing that with our new camera setup multi view may be unnecessary so it's not a huge issue at the moment

**Comment by vwout** [comment]
Thank you for the feedback. Since commit [dce5b42](https://github.com/vwout/obs-visca-control/commit/dce5b4265d423e5ab9445170ef7f592c863c24a2), the commands should work properly also i multiview mode, as listed i the overview in the readme.

I will close this issue. Feel free to report additional findings.

**Comment by vwout** [comment]
Hi @rtalking10, have you by any change seen issue #16? This is related to what you have reported; it turned out that it was not working correctly in normal mode (with one screen, instead of studio mode). Additionally, stop actions were not executed when the new active scene also contains actions for the same Visca controlled camera. That should be resolved in 2e231e2.

**Comment by rtalking10** [comment]
Hey I haven't seen any issues for us recently but I work almost exclusively in studio mode, which has been working
