### ISSUE TITLE
Want to capture camera current PTZ values and save them in the scene

### ISSUE THREAD

**Issue by tmimlitch** [vwout/obs-visca-control#4]
Here are my versions of your control and libvisca LUA scripts for your review/comment etc. Ive only changed the names so my development work remained separate from your original scripts

[obs-visca-controlPTZ_V3.zip](https://github.com/vwout/obs-visca-control/files/9077789/obs-visca-controlPTZ_V3.zip)
.

**Comment by tmimlitch** [comment]
[obs_client_server_simulator.zip](https://github.com/vwout/obs-visca-control/files/9078018/obs_client_server_simulator.zip)

I dont have a cam at home to test with eithe so I wrote some client server scripts to simulate the inquire and control side without really doing anything but sending canned responses.  I only needed the PTZ labeled script and ran in on an old PC (still W7) under OBS, would iniialize it via the Start and Receive buttons,  Then could run my/your script on my current PC and test and debug it.

**Comment by CapsAdmin** [comment]
Wouldn't it be easier to review the changes if you made a pull request? If you're not familiar with how, there are plenty of tutorials on youtube.

I don't have a camera to test with either, so the simulator scripts seem useful as well. (I'm mostly interested in this project because of the luajitsocket library I made.)

**Comment by tmimlitch** [comment]
Thank you for your suggestion.  Ive never worked in this environment before so i didnt know the process.  Ill go back and learn it thanks.  
I made no changed to your luajitsocket script, indeed i barely understood it at all.  But it is certainly the foundation for all this script.  
Vwout is already looking at correcting my crude patchwork. And at his suggestion that i used this method to be able to upload my mods for him to look at.
Thanks again.  ToM.

Sent from Yahoo Mail on Android 
 
  On Sun, Jul 10, 2022 at 2:28 AM, Elias ***@***.***> wrote:   


Wouldn't it be easier to review the changes if you made a pull request. If you're not familiar with how, there are plenty of tutorials on youtube.

I don't have a camera to test with either, so the simulator scripts seem useful as well. (I'm mostly interested in this project because of the luajitsocket library I made.)

**Comment by vwout** [comment]
The suggested changes and new features have been implemented in the main branch, ready for testing.
Note: this requires a camera that send responses on same socket that send the command to the camera.

**Comment by vwout** [comment]
Implementation is confirmed on Everet cameras. Will be available as of next release (or immediately from source).

**Comment by tmimlitch** [comment]
Vwout,
Thanks again.  Ive been battling several medical issues and tested positive for covid.  Think im over the hump, but ive been out of action for a while.  Ill try to test your latest out this week.  
ToM.

Sent from Yahoo Mail on Android 
 
  On Sun, Sep 4, 2022 at 4:30 PM, ***@***.***> wrote:   


Implementation is confirmed on Everet cameras. Will be available as of next release (or immediately from source).

**Comment by tmimlitch** [comment]
vwout,
I finally got to try out your latest obs-visca-control (09/02/2022 i believe), and it worked great.  I ran it thru its paces on one camera with four scenes and various absolute locations.  I did have to press the retrieve current position button twice to get the values to display, but that is fine.  Loved your user interface and the speed control too.  I looked briefly at your code changes and I am in awe,  it would take me another lifetime to figure all that out.  Thank you for all your fantastic work on this.  

I've attached my scenes json file below of this test run.
ToM.
