### ISSUE TITLE
Unable to load script

### ISSUE THREAD

**Issue by PoWeR-Ding** [vwout/obs-visca-control#5]
@vwout 

As shown in the following figure：
![微信截图_20221009160930](https://user-images.githubusercontent.com/112599924/194745466-50ccf743-b529-4cb5-92c7-a9c77685b3f6.png)

![微信截图_20221009161017](https://user-images.githubusercontent.com/112599924/194745475-42b864c7-8428-4024-9135-c5f315f4db67.png)

**Comment by CapsAdmin** [comment]
can you post the full log?

**Comment by PoWeR-Ding** [comment]
@CapsAdmin  

[Crash 2022-10-09 16-44-44.txt](https://github.com/vwout/obs-visca-control/files/9741173/Crash.2022-10-09.16-44-44.txt)

**Comment by PoWeR-Ding** [comment]
@CapsAdmin  
[Crash 2022-10-09 16-08-52.txt](https://github.com/vwout/obs-visca-control/files/9741190/Crash.2022-10-09.16-08-52.txt)

**Comment by CapsAdmin** [comment]
Hmm, assuming it's AddPath crashing it could be related to this

**Comment by CapsAdmin** [comment]
hmm, assuming it's this causing the crash
https://github.com/vwout/obs-visca-control/blob/main/obs-visca-control.lua#L720

it could be related to your unusual obs location. What happens if you put it obs directly under `c:\users\72709\desktop\obs\*` without any chinese characters?

**Comment by PoWeR-Ding** [comment]
@CapsAdmin 

The 1.6 version runs normally.
↓↓↓↓↓↓↓↓
![微信截图_20221009224108](https://user-images.githubusercontent.com/112599924/194763171-cc1948cd-d5e1-480c-b33b-2c8c8b04a082.png)



2.0 version
↓↓↓↓↓↓↓↓
![微信截图_20221009224131](https://user-images.githubusercontent.com/112599924/194763189-5137f405-029a-4fc8-a686-09201957b47b.png)

![微信截图_20221009224152](https://user-images.githubusercontent.com/112599924/194763197-9354ab7a-931f-44c6-af6e-7302725ec4ab.png)

[Crash 2022-10-09 22-41-45.txt](https://github.com/vwout/obs-visca-control/files/9741814/Crash.2022-10-09.22-41-45.txt)

**Comment by vwout** [comment]
@CapsAdmin is probably right
> hmm, assuming it's this causing the crash https://github.com/vwout/obs-visca-control/blob/main/obs-visca-control.lua#L720
> 

Can you remove line 720 from obs-visca-control.lua?

When that does not crash, add the following line at the location at line 720:
```obs.obs_properties_add_path(backup_props, "backup_file", "Backup file", obs.OBS_PATH_FILE_SAVE, "*.json", nil)```

**Comment by PoWeR-Ding** [comment]
@vwout 

 remove line 720 from obs-visca-control.lua，and then the script loading is normal. √√√√√
↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓

![微信截图_20221010100221](https://user-images.githubusercontent.com/112599924/194790903-094c7597-e8fe-46a2-b51e-1c425229ed13.png)
![微信截图_20221010101248](https://user-images.githubusercontent.com/112599924/194790907-e83f5ac9-504e-4e21-aee9-ff729dbdc504.png)

add the following line at the location at line 720:
obs.obs_properties_add_path(backup_props, "backup_file", "Backup file", obs.OBS_PATH_FILE_SAVE, "*.json", nil)
↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓

![微信截图_20221010101415](https://user-images.githubusercontent.com/112599924/194790966-96120f64-6022-4d6f-9bca-a9c9b228c467.png)


[Crash 2022-10-10 10-14-07.txt](https://github.com/vwout/obs-visca-control/files/9743082/Crash.2022-10-10.10-14-07.txt)

**Comment by vwout** [comment]
Thanks for the confirmation.
The code seems to contain a bug, where two arguments are reversed (the search path 'nil' and the file filter '*.json'). The crash however persists, so that seems to be a bug in OBS.

When you leave out the lines 719-723, the plugin will fully work. Only the ability to backup and restore settings is removed.
I will try to check the issue with OBS.

**Comment by PoWeR-Ding** [comment]
@vwout 
Thank you very much for your handling.

**Comment by vwout** [comment]
There is one more thing you could check in case you are in the position to install and test OBS 28.
OBS 28 does contain some breaking changes (and NDI does not work yet), so you might not want to do that.
But in case you do, it would be interesting to see if the issue is resolved. OBS 28 contains an updated graphics library (QT6).

I can't test this for you unfortunately. The issue seems to be related to the use of Chinese (unicode or multibyte character sets) since I can't reproduce it on an English Windows distribution.

**Comment by vwout** [comment]
@PoWeR-Ding were you by any chance able to test with OBS 28?

**Comment by PoWeR-Ding** [comment]
@vwout 
Sorry, I ignored it a while ago.

This problem has been solved on OBS 28.

![微信截图_20221021135722](https://user-images.githubusercontent.com/112599924/197123548-59d08b56-3e2a-4bad-b52f-111139418f75.png)
![微信截图_20221021135758](https://user-images.githubusercontent.com/112599924/197123570-2b79b48d-e7a9-47a5-ba2b-62a795fc3859.png)
![微信截图_20221021135819](https://user-images.githubusercontent.com/112599924/197123591-84d28ff5-9fb2-4486-a99b-a3a8ecd8a4aa.png)

**Comment by PoWeR-Ding** [comment]
@vwout 
It should be that the OBS built by myself cannot be used.

I use the normal one on the official website OBS 27.

![微信截图_20221021142956](https://user-images.githubusercontent.com/112599924/197128484-24bef29d-57bf-4671-a56e-c4b5e5b1b2ea.png)

**Comment by vwout** [comment]
To be sure I understand: it does work with the official release of both OBS 27 and 28?
The issue only occurs on your own build?

**Comment by PoWeR-Ding** [comment]
yep. sorry.

The current test is indeed like this.

**Comment by vwout** [comment]
Thanks for confirming. Then the fix in f0fed4975021c2a392c08fe1f568c0d8c52a8e5c concludes this ticket.
